"""added tables

Revision ID: 13f4d4f58408
Revises: 
Create Date: 2026-04-19 12:55:30.411631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f4d4f58408'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('delay_reason', sa.String(), nullable=True),
    sa.Column('final_status', sa.String(), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('reason_flag', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_ts', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_records_id'), 'evaluation_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_records_id'), table_name='evaluation_records')
    op.drop_table('evaluation_records')
    # ### end Alembic commands ###
